// Fallback pre-seeded data used if database connection is unavailable
export const FALLBACK_BRANCHES = [
  {
    id: 'branch-downtown-1',
    name: 'Downtown Flagship',
    address: '142 Market Street, Financial District',
    latitude: 37.7892,
    longitude: -122.4014,
    phone: '(415) 555-0142',
    opening_hours: {
      monday: '08:00 - 22:00',
      tuesday: '08:00 - 22:00',
      wednesday: '08:00 - 22:00',
      thursday: '08:00 - 23:00',
      friday: '08:00 - 00:00',
      saturday: '09:00 - 00:00',
      sunday: '09:00 - 21:00',
    },
    is_active: true,
    tables: [
      { id: 't-1', label: 'Table 1' },
      { id: 't-2', label: 'Table 2' },
      { id: 't-3', label: 'Table 3' },
      { id: 't-4', label: 'Table 4' },
      { id: 't-5', label: 'Table 5' },
      { id: 't-p1', label: 'Patio 1' },
      { id: 't-p2', label: 'Patio 2' },
      { id: 't-b1', label: 'Bar 1' },
      { id: 't-b2', label: 'Bar 2' },
    ],
  },
  {
    id: 'branch-uptown-2',
    name: 'Uptown Garden & Patio',
    address: '884 Columbus Avenue, North Beach',
    latitude: 37.8015,
    longitude: -122.4148,
    phone: '(415) 555-0884',
    opening_hours: {
      monday: '09:00 - 22:00',
      tuesday: '09:00 - 22:00',
      wednesday: '09:00 - 22:00',
      thursday: '09:00 - 22:00',
      friday: '09:00 - 23:30',
      saturday: '10:00 - 23:30',
      sunday: '10:00 - 21:00',
    },
    is_active: true,
    tables: [
      { id: 't-u1', label: 'Table 1' },
      { id: 't-u2', label: 'Table 2' },
      { id: 't-u3', label: 'Patio 1' },
      { id: 't-u4', label: 'Patio 2' },
    ],
  },
  {
    id: 'branch-marina-3',
    name: 'Marina Waterfront',
    address: '2240 Chestnut Street, Marina',
    latitude: 37.7998,
    longitude: -122.4412,
    phone: '(415) 555-2240',
    opening_hours: {
      monday: '08:30 - 21:30',
      tuesday: '08:30 - 21:30',
      wednesday: '08:30 - 21:30',
      thursday: '08:30 - 22:00',
      friday: '08:30 - 23:00',
      saturday: '09:00 - 23:00',
      sunday: '09:00 - 21:00',
    },
    is_active: true,
    tables: [
      { id: 't-m1', label: 'Table 1' },
      { id: 't-m2', label: 'Table 2' },
      { id: 't-m3', label: 'Waterfront 1' },
    ],
  },
];

export const FALLBACK_MENU_CATEGORIES = [
  {
    id: 'cat-mains',
    name: 'Mains & Specialties',
    sort_order: 1,
    items: [
      {
        id: 'item-ribeye',
        category_id: 'cat-mains',
        name: 'Truffle Butter Ribeye',
        description: 'Charred 12oz prime ribeye topped with compound black truffle butter, served with roasted rosemary fingerlings and blistered asparagus.',
        price: 36.0,
        image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [
          { id: 'm-1', name: 'Rare', price_delta: 0, group_name: 'Meat Temperature', is_required: true },
          { id: 'm-2', name: 'Medium Rare', price_delta: 0, group_name: 'Meat Temperature', is_required: true },
          { id: 'm-3', name: 'Medium', price_delta: 0, group_name: 'Meat Temperature', is_required: true },
          { id: 'm-4', name: 'Extra Truffle Butter', price_delta: 3.5, group_name: 'Add-ons', is_required: false },
        ],
      },
      {
        id: 'item-salmon',
        category_id: 'cat-mains',
        name: 'Pan-Seared Pacific Salmon',
        description: 'Crispy skin wild-caught salmon over celery root puree, charred broccolini, and a lemon-caper beurre blanc.',
        price: 28.5,
        image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [],
      },
      {
        id: 'item-burger',
        category_id: 'cat-mains',
        name: 'Smoked Gouda Burger',
        description: 'Half-pound dry-aged beef patty, applewood bacon, melted smoked gouda, onion jam, and garlic aioli on a brioche bun.',
        price: 19.5,
        image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [
          { id: 'm-b1', name: 'Single Patty (8oz)', price_delta: 0, group_name: 'Size', is_required: true },
          { id: 'm-b2', name: 'Double Patty (16oz)', price_delta: 5.5, group_name: 'Size', is_required: true },
          { id: 'm-b3', name: 'Avocado Slices', price_delta: 2.5, group_name: 'Add-ons', is_required: false },
        ],
      },
    ],
  },
  {
    id: 'cat-pizza',
    name: 'Wood-Fired Pizza',
    sort_order: 2,
    items: [
      {
        id: 'item-margherita',
        category_id: 'cat-pizza',
        name: 'Margherita Burrata D.O.P.',
        description: 'San Marzano tomato sauce, fresh creamy burrata, sweet basil oil, and Maldon sea salt flakes.',
        price: 21.0,
        image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [
          { id: 'm-p1', name: 'Regular Crust (12")', price_delta: 0, group_name: 'Crust Size', is_required: true },
          { id: 'm-p2', name: 'Large Family Crust (16")', price_delta: 6.0, group_name: 'Crust Size', is_required: true },
        ],
      },
      {
        id: 'item-mushroom',
        category_id: 'cat-pizza',
        name: 'Wild Mushroom & Taleggio',
        description: 'Roasted cremini and shiitake mushrooms, melted taleggio cheese, thyme, white truffle oil on garlic cream base.',
        price: 23.5,
        image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [],
      },
    ],
  },
  {
    id: 'cat-starters',
    name: 'Starters & Salads',
    sort_order: 3,
    items: [
      {
        id: 'item-ricotta',
        category_id: 'cat-starters',
        name: 'Whipped Ricotta Crostini',
        description: 'House-whipped sheep milk ricotta, lavender wildflower honey, crushed pistachios on sourdough crostini.',
        price: 14.0,
        image_url: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [],
      },
    ],
  },
  {
    id: 'cat-beverages',
    name: 'Artisan Beverages',
    sort_order: 4,
    items: [
      {
        id: 'item-spritz',
        category_id: 'cat-beverages',
        name: 'Smoked Blood Orange Spritz',
        description: 'Italian blood orange reduction, smoked rosemary syrup, prosecco, and sparkling mineral water.',
        price: 9.5,
        image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [],
      },
      {
        id: 'item-latte',
        category_id: 'cat-beverages',
        name: 'Cold Brew Oat Latte',
        description: 'Single-origin Ethiopian cold brew coffee infused with creamy organic oat milk and vanilla bean syrup.',
        price: 6.5,
        image_url: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [],
      },
    ],
  },
  {
    id: 'cat-desserts',
    name: 'House Desserts',
    sort_order: 5,
    items: [
      {
        id: 'item-lava',
        category_id: 'cat-desserts',
        name: 'Pistachio Lava Cake',
        description: 'Warm Sicilian pistachio cake with a molten white chocolate core, served with salted caramel gelato.',
        price: 13.0,
        image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [],
      },
      {
        id: 'item-tiramisu',
        category_id: 'cat-desserts',
        name: 'Traditional Tiramisu Classico',
        description: 'Espresso-soaked savoiardi ladyfingers layered with rich mascarpone zabaglione and Valrhona cocoa.',
        price: 11.5,
        image_url: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
        is_available: true,
        modifiers: [],
      },
    ],
  },
];

export const FALLBACK_USERS = [
  {
    id: 'u-admin-1',
    name: 'Elena Rostova (Admin)',
    email: 'admin@restaurant.com',
    password: 'admin123',
    role: 'admin',
    branch_id: null,
    branch: null,
  },
  {
    id: 'u-emp-downtown',
    name: 'Marcus Vance',
    email: 'downtown@restaurant.com',
    password: 'password123',
    role: 'employee',
    branch_id: 'branch-downtown-1',
    branch: { id: 'branch-downtown-1', name: 'Downtown Flagship' },
  },
  {
    id: 'u-emp-uptown',
    name: 'Sophia Lin',
    email: 'uptown@restaurant.com',
    password: 'password123',
    role: 'employee',
    branch_id: 'branch-uptown-2',
    branch: { id: 'branch-uptown-2', name: 'Uptown Garden & Patio' },
  },
];
